services:
  db:
    image: postgres:16.2-bookworm
    container_name: squirrelcloud-production-database
    restart: always
    environment:
      POSTGRES_USER: squirrelcloud
      POSTGRES_PASSWORD: squirrelcloud
      POSTGRES_DB: squirrelcloud
    volumes:
      - ./db:/var/lib/postgresql/data

  backend:
    image: squirrelcloud:latest
    container_name: squirrelcloud-production-backend
    restart: always
    volumes:
      - ./file:/file
      - ./logs:/logs
      - ./backup:/backup
      - ./src:/app
    ports:
      - "5000:443"
    depends_on:
      - db